implementation of fortify on demand scan
hmcts/fortify-client pull request #1
Opened 2021-06-29 10:23 UTC by kaanaktas

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2021-06-29 12:13 UTC, MSancaktutar commented on src/main/java/uk.gov.hmcts.fodscanner/FailureLevel.java
> +public enum FailureLevel {
rename to pls Severity

2021-06-29 12:15 UTC, MSancaktutar commented on src/main/java/uk.gov.hmcts.fodscanner/PropertiesSingleton.java
> +    private Properties getPropertiesFromFile() throws Exception {
rename to getPropertiesFromResource please

2021-06-30 08:57 UTC, kaanaktas commented on src/main/java/uk.gov.hmcts.fodscanner/FailureLevel.java
> +public enum FailureLevel {
done

2021-06-30 08:57 UTC, kaanaktas commented on src/main/java/uk.gov.hmcts.fodscanner/PropertiesSingleton.java
> +    private Properties getPropertiesFromFile() throws Exception {
done

2021-07-01 14:12 UTC, MSancaktutar commented on src/test/java/uk/gov/hmcts/fortifyclient/FortifyClientTest.java
> +}
eol at eof, always

2021-07-01 14:13 UTC, MSancaktutar commented on src/test/java/uk/gov/hmcts/fortifyclient/ScanReportTest.java
> +    void isSuccessful() {
better name for test methods that tells what they are testing. pls see examples from ccd repos for good naming examples.

2021-07-01 14:15 UTC, MSancaktutar requested changes
Please replace all std outs with debug / info / error logs, whichever more appropriate at each point.

2021-07-01 14:17 UTC, MSancaktutar reviewed
A lot more unit and integration tests would be required, but that can be done under a tech debt ticket, to be actioned by any contributor later on. I'll be happy to release this if comments before all fully applied.

2021-07-01 15:21 UTC, kaanaktas commented on src/test/java/uk/gov/hmcts/fortifyclient/FortifyClientTest.java
> +}
done

2021-07-01 15:21 UTC, kaanaktas commented on src/test/java/uk/gov/hmcts/fortifyclient/ScanReportTest.java
> +    void isSuccessful() {
done

2021-07-01 19:19 UTC, MSancaktutar commented on src/test/java/uk/gov/hmcts/fortifyclient/ScanReportTest.java
> +}
eol at eof

2021-07-01 19:19 UTC, MSancaktutar commented on src/test/java/uk/gov/hmcts/fortifyclient/FolderZipperTest.java
> +}
eol at eof

2021-07-01 19:19 UTC, MSancaktutar commented on src/main/resources/ReportTemplate.html
> +</html>
eol at eof

2021-07-01 22:16 UTC, MSancaktutar approved these changes
LGTM

2021-07-01 22:17 UTC, merged

2021-07-01 22:19 UTC, MSancaktutar commented
Need more unit and integration tests and a few more minor improvements could be made, but they can be done by a next contributor. Good enough to release as an initial, stable release.